version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

# Anchors to prevent forgetting to update a version
os_version: &os_version ubuntu24
baselibs_version: &baselibs_version v8.32.0
bcs_version: &bcs_version v12.0.0
tag_build_arg_name: &tag_build_arg_name gcmversion

orbs:
  ci: geos-esm/circleci-tools@5

workflows:
  build-test:
    jobs:
      - ci/build:
          name: build-GEOSadas-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [ifort]
          resource_class: xlarge
          baselibs_version: *baselibs_version
          repo: GEOSadas
          persist_workspace: false # Needs to be true to run fv3/gcm experiment, costs extra
          mepodevelop: false
          rebuild_procs: 4
          build_type: Release
