#!/bin/bash

MYNAME="ldas_add2rc"
if [[ $# -ne 2 ]]; then 
   echo " "
   echo " NAME "
   echo " "
   echo "  $MYNAME  - precedure to add/verify land premeters in AGCM.rc "
   echo " "
   echo " SYNOPSIS  "
   echo " "
   echo "  $MYNAME  FVHOME  LDHOME"
   echo " "
   echo " where"
   echo "   FVHOME  -  location of  adas experiment "
   echo "   LDHOME  -  location of  ldas experiment "
   echo " "
   echo " DESCRIPTION"
   echo " "
   echo "    This procedure inserts additional land parameters in AGCM.rc" 
   echo "    and verify if land parameters in AGCM.rc are consistent "
   echo "    with LDAS.rc in LADAS experiment "
   echo " "
   echo "   It should be run after fvsetup and ldas_setup  "
   exit 0
fi

FVHOME="$1" 
LDHOME="$2" 

cd $FVHOME/run
cp AGCM.rc.tmpl  AGCM.rc.tmpl.original 

list="LANDASSIM_DT LANDASSIM_T0 "
  for var in $list
do
    grep $var $LDHOME/run/LDAS.rc >> add.txt
done

sed -i '/LDAS_INCR/r add.txt' AGCM.rc.tmpl

echo " The following land parameters are added to AGCM.rc: " 
for var in $list
do
echo "$(grep $var add.txt)"
done

clist=" Z0_FORMULATION:.*  LAND_PARAMS:.*  LSM_CHOICE:.* "
  for var in $clist 
do 
Lset="$(grep $var $LDHOME/run/LDAS.rc)"
Aset="$(grep $var $FVHOME/run/AGCM.rc.tmpl)"
lv="$(echo $Lset | cut -d " " -f 2)"
av="$(echo $Aset | cut -d " " -f 2)"
if [ "$lv" != "$av" ]; then
echo " " 
echo "Please make the following parameter value consistent in AGCM.rc and LDAS.rc:"
echo "in AGCM.rc: $Aset "  
echo "in LDAS.rc: $Lset "
echo " " 
fi 
done   

###atmens
mv add.txt $FVHOME/run/atmens/. 
cd $FVHOME/run/atmens/ 
cp AGCM.rc.tmpl AGCM.rc.tmpl.original 

sed -i '/LDAS_INCR/r add.txt' AGCM.rc.tmpl

rm -rf add.txt
